ALTER TABLE ZMS_USR.USER ADD COLUMN ADDRESS VARCHAR(512);
ALTER TABLE ZMS_USR.USER ADD COLUMN VERSION INT DEFAULT 0;
ALTER TABLE ZMS_USR.USER ADD COLUMN PHONE VARCHAR(100);
ALTER TABLE ZMS_USR.USER ADD COLUMN TYPE INT NOT NULL ;
ALTER TABLE ZMS_USR.USER RENAME COLUMN ID TO USER_ID;
ALTER TABLE ZMS_USR.USER RENAME COLUMN USERNAME TO USER_NAME;